
import { Phrase, Lesson, SalahStep, LegacyProject, Product } from './types';

export const INITIAL_PHRASES: Phrase[] = [
  {
    id: 'subhanallah',
    arabic: 'سُبْحَانَ ٱللَّٰهِ',
    transliteration: 'SubhanAllah',
    translation: 'Glory be to Allah',
  },
  {
    id: 'alhamdulillah',
    arabic: 'ٱلْحَمْدُ لِلَّٰهِ',
    transliteration: 'Alhamdulillah',
    translation: 'Praise be to Allah',
  },
  {
    id: 'allahu-akbar',
    arabic: 'ٱللَّٰهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: 'Allah is the Greatest',
  },
  {
    id: 'astaghfirullah',
    arabic: 'أَسْتَغْفِرُ ٱللَّٰهَ',
    transliteration: 'Astaghfirullah',
    translation: 'I seek forgiveness from Allah',
  },
  {
    id: 'la-ilaha-illallah',
    arabic: 'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ',
    transliteration: 'La ilaha illallah',
    translation: 'There is no god but Allah',
  }
];

export const ALLAH_NAMES: Phrase[] = [
  { id: 'n1', arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman', translation: 'The Beneficent' },
  { id: 'n2', arabic: 'الرَّحِيمُ', transliteration: 'Ar-Rahim', translation: 'The Merciful' },
  { id: 'n3', arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', translation: 'The Eternal Lord' },
  { id: 'n4', arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', translation: 'The Most Sacred' },
  { id: 'n5', arabic: 'السَّلَامُ', transliteration: 'As-Salam', translation: 'The Source of Peace' },
  { id: 'n6', arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu’min', translation: 'The Infuser of Faith' },
  { id: 'n7', arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', translation: 'The Guardian' },
  { id: 'n8', arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', translation: 'The Almighty' },
  { id: 'n9', arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', translation: 'The Compeller' },
  { id: 'n10', arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', translation: 'The Supreme' },
  { id: 'n11', arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', translation: 'The Creator' },
  { id: 'n12', arabic: 'الْبَارِئُ', transliteration: 'Al-Bari', translation: 'The Evolver' },
  { id: 'n13', arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', translation: 'The Fashioner' },
  { id: 'n14', arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', translation: 'The Constant Forgiver' },
  { id: 'n15', arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', translation: 'The All-Prevailing' },
  { id: 'n16', arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', translation: 'The Supreme Bestower' },
  { id: 'n17', arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', translation: 'The Provider' },
  { id: 'n18', arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', translation: 'The Opener' },
  { id: 'n19', arabic: 'الْعَلِيمُ', transliteration: 'Al-Alim', translation: 'The All-Knowing' },
  { id: 'n20', arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', translation: 'The Withholder' },
  { id: 'n21', arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', translation: 'The Extender' },
  { id: 'n22', arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', translation: 'The Reducer' },
  { id: 'n23', arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi', translation: 'The Exalter' },
  { id: 'n24', arabic: 'الْمُعِزُّ', transliteration: 'Al-Mu’izz', translation: 'The Bestower of Honor' },
  { id: 'n25', arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', translation: 'The Humiliator' },
  { id: 'n26', arabic: 'السَّمِيعُ', transliteration: 'As-Sami', translation: 'The All-Hearing' },
  { id: 'n27', arabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', translation: 'The All-Seeing' },
  { id: 'n28', arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', translation: 'The Judge' },
  { id: 'n29', arabic: 'الْعَدْلُ', transliteration: 'Al-Adl', translation: 'The Utterly Just' },
  { id: 'n30', arabic: 'اللَّطِيفُ', transliteration: 'Al-Latif', translation: 'The Subtle One' },
  { id: 'n31', arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', translation: 'The All-Aware' },
  { id: 'n32', arabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', translation: 'The Forbearing One' },
  { id: 'n33', arabic: 'الْعَظِيمُ', transliteration: 'Al-Azim', translation: 'The Magnificent' },
  { id: 'n34', arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafur', translation: 'The Great Forgiver' },
  { id: 'n35', arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakur', translation: 'The Most Appreciative' },
  { id: 'n36', arabic: 'الْعَلِيُّ', transliteration: 'Al-Ali', translation: 'The Most High' },
  { id: 'n37', arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', translation: 'The Most Great' },
  { id: 'n38', arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', translation: 'The Preserver' },
  { id: 'n39', arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', translation: 'The Sustainer' },
  { id: 'n40', arabic: 'الْحَسِيبُ', transliteration: 'Al-Hasib', translation: 'The Reckoner' },
  { id: 'n41', arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', translation: 'The Majestic' },
  { id: 'n42', arabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', translation: 'The Most Generous' },
  { id: 'n43', arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', translation: 'The Watchful' },
  { id: 'n44', arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', translation: 'The Responsive One' },
  { id: 'n45', arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi', translation: 'The All-Encompassing' },
  { id: 'n46', arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', translation: 'The All-Wise' },
  { id: 'n47', arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', translation: 'The Most Loving' },
  { id: 'n48', arabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', translation: 'The Glorious' },
  { id: 'n49', arabic: 'الْبَاعِثُ', transliteration: 'Al-Ba’ith', translation: 'The Resurrector' },
  { id: 'n50', arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid', translation: 'The Witness' },
  { id: 'n51', arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', translation: 'The Absolute Truth' },
  { id: 'n52', arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakil', translation: 'The Trustee' },
  { id: 'n53', arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawi', translation: 'The All-Strong' },
  { id: 'n54', arabic: 'الْمَتِينُ', transliteration: 'Al-Matin', translation: 'The Firm One' },
  { id: 'n55', arabic: 'الْوَلِيُّ', transliteration: 'Al-Wali', translation: 'The Protecting Associate' },
  { id: 'n56', arabic: 'الْحَمِيدُ', transliteration: 'Al-Hamid', translation: 'The Praiseworthy' },
  { id: 'n57', arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', translation: 'The All-Enumerating' },
  { id: 'n58', arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi', translation: 'The Originator' },
  { id: 'n59', arabic: 'الْمُعِيدُ', transliteration: 'Al-Mu’id', translation: 'The Restorer' },
  { id: 'n60', arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', translation: 'The Giver of Life' },
  { id: 'n61', arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumit', translation: 'The Bringer of Death' },
  { id: 'n62', arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', translation: 'The Ever-Living' },
  { id: 'n63', arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyum', translation: 'The Sustainer' },
  { id: 'n64', arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', translation: 'The Perceiver' },
  { id: 'n65', arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', translation: 'The Illustrious' },
  { id: 'n66', arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', translation: 'The One' },
  { id: 'n67', arabic: 'الْأَحَدُ', transliteration: 'Al-Ahad', translation: 'The Unique' },
  { id: 'n68', arabic: 'الصَّمَدُ', transliteration: 'As-Samad', translation: 'The Eternal' },
  { id: 'n69', arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', translation: 'The Capable' },
  { id: 'n70', arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', translation: 'The Omnipotent' },
  { id: 'n71', arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', translation: 'The Expediter' },
  { id: 'n72', arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Mu’akhkhir', translation: 'The Delayer' },
  { id: 'n73', arabic: 'الْأَوَّلُ', transliteration: 'Al-Awwal', translation: 'The First' },
  { id: 'n74', arabic: 'الْأٓخِرُ', transliteration: 'Al-Akhir', translation: 'The Last' },
  { id: 'n75', arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', translation: 'The Manifest' },
  { id: 'n76', arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', translation: 'The Hidden One' },
  { id: 'n77', arabic: 'الْوَالِي', transliteration: 'Al-Wali', translation: 'The Governor' },
  { id: 'n78', arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta’ali', translation: 'The Self Exalted' },
  { id: 'n79', arabic: 'الْبَرُّ', transliteration: 'Al-Barr', translation: 'The Source of Goodness' },
  { id: 'n80', arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', translation: 'The Ever-Relenting' },
  { id: 'n81', arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', translation: 'The Avenger' },
  { id: 'n82', arabic: 'الْعَفُوُّ', transliteration: 'Al-Afu', translation: 'The Pardoner' },
  { id: 'n83', arabic: 'الرَّؤُوفُ', transliteration: 'Ar-Ra’uf', translation: 'The Most Kind' },
  { id: 'n84', arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', translation: 'Master of the Kingdom' },
  { id: 'n85', arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Dhul-Jalal wal-Ikram', translation: 'Possessor of Glory' },
  { id: 'n86', arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', translation: 'The Equitable' },
  { id: 'n87', arabic: 'الْجَامِعُ', transliteration: 'Al-Jami', translation: 'The Gatherer' },
  { id: 'n88', arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghani', translation: 'The Self-Sufficient' },
  { id: 'n89', arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', translation: 'The Enricher' },
  { id: 'n90', arabic: 'الْمَانِعُ', transliteration: 'Al-Mani', translation: 'The Withholder' },
  { id: 'n91', arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', translation: 'The Distresser' },
  { id: 'n92', arabic: 'النَّافِعُ', transliteration: 'An-Nafi', translation: 'The Propitious' },
  { id: 'n93', arabic: 'النُّورُ', transliteration: 'An-Nur', translation: 'The Light' },
  { id: 'n94', arabic: 'الْهَادِي', transliteration: 'Al-Hadi', translation: 'The Guide' },
  { id: 'n95', arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi', translation: 'The Incomparable' },
  { id: 'n96', arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', translation: 'The Everlasting' },
  { id: 'n97', arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', translation: 'The Inheritor' },
  { id: 'n98', arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', translation: 'The Guide to the Right Path' },
  { id: 'n99', arabic: 'الصَّبُورُ', transliteration: 'As-Sabur', translation: 'The Patient One' }
];

export const DEMO_PROFILES: any[] = [];

export const INITIAL_LESSONS: Lesson[] = [
  { id: 'foundations-1', title: 'Foundations (Shahada)', description: 'The 6 Pillars of Iman & 5 Pillars of Islam.', level: 1, creditReward: 5.00, category: 'Foundations' },
  { id: 'prayer-1', title: 'The Gift of Prayer', description: 'Step-by-step Wudu and Salah guide.', level: 2, creditReward: 10.00, category: 'Prayer' },
  { id: 'character-1', title: 'Prophetic Character', description: 'Adab and Akhlaq in daily life.', level: 3, creditReward: 15.00, category: 'Character', isLocked: true },
  { id: 'quran-1', title: 'The Living Word', description: 'Understanding the miraculous nature of Quran.', level: 4, creditReward: 20.00, category: 'Qur’an', isLocked: true }
];

export const INITIAL_PROJECTS: LegacyProject[] = [];

export const INITIAL_PRODUCTS: Product[] = [];

export const STORAGE_KEYS = {
  STATS: 'zikr_v3_stats',
  SETTINGS: 'zikr_v3_settings'
};
